M48
; DRILL file {KiCad 9.0.4-208-g72db7bfedc} date 2026-05-13T15:04:08+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-13T15:04:08+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4-208-g72db7bfedc
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X97.94Y-91.84
X97.94Y-98.44
T2
X93.75Y-63.75
X93.75Y-106.25
X221.25Y-63.75
X221.25Y-106.25
M30
